version: "3.9"

services:
  db:
    image: mysqldb
    container_name: mysqldb
    build:
      context: .
      dockerfile: Containerfile.db
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - mynet

  app:
    image: podman-app
    container_name: flaskapp
    build:
      context: .
      dockerfile: Containerfile
    depends_on:
      - db
    ports:
      - "5000:5000"
    networks:
      - mynet

volumes:
  dbdata:

networks:
  mynet:

